# Generated by Django 4.1.2 on 2022-11-07 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='fechaCompletada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
